feat: add support for electron_debug.log
tinyspeck/sleuth pull request #61
Opened 2023-03-08 02:32 UTC by erickzhao

This PR adds support for `electron_debug.log` in Sleuth. Chromium logs have a unique format that requires a whole other set of parsers.

A log line looks something like this:
```
[85509:0307/160606.126448:WARNING:transport_feedback_adapter.cc(263)] Failed to lookup send time for 1 packet. Send time history too small?
```

Here, the metadata prefixing the message is `[process_id:MMDD/hhmmss.SSSSSS:LOG_LEVEL:filename(line)]` as documented in https://support.google.com/chrome/a/answer/6271282.

Some notes:
* The timestamp is approximate: we don't have year information, but we assume that logs are fresh and sent within the last year or so.
* Log levels are not standard, so I mapped some obvious ones to the ones that Sleuth uses.
* We can actually link to Chrome's source to find the code where the log file lives! For example: https://source.chromium.org/chromium/chromium/src/+/main:third_party/webrtc/modules/congestion_controller/rtp/transport_feedback_adapter.cc?q=filepath:transport_feedback_adapter.cc&ss=chromium

2023-03-13 18:29 UTC, nocturnll requested changes

2023-03-13 18:29 UTC, nocturnll commented on src/renderer/processor.ts
> +const CHROMIUM_RGX = /^\[(\d+:\d{4}\/\d{6}\.\d{6}:[a-zA-Z]+:.*\(\d+\))\] (.*)$/;
make it `const CHROMIUM_RGX = /^\[(\d+:\d{4}\/\d{6}\.\d{3,6}:[a-zA-Z]+:.*\(\d+\))\] (.*)$/;`
some logs have 3 digits for milliseconds and some have 6

2023-03-14 21:44 UTC, erickzhao commented on src/renderer/processor.ts
> +const CHROMIUM_RGX = /^\[(\d+:\d{4}\/\d{6}\.\d{6}:[a-zA-Z]+:.*\(\d+\))\] (.*)$/;
[5ee4a08](https://github.com/tinyspeck/sleuth/pull/61/commits/5ee4a08e72218d2dcaea85a8f94e9095815edb3b)

2023-03-14 22:21 UTC, nocturnll approved these changes

2023-03-29 22:29 UTC, merged

2023-03-29 22:45 UTC, erickzhao commented
pog